name: PR verify

on:
  pull_request_target:
    types: [opened, edited, synchronize, reopened]

permissions:
  checks: write # Allow access to checks to write check runs.

jobs:
  verify:
    runs-on: ubuntu-latest
    name: Verify PR contents
    steps:
      - name: Verifier action
        id: verifier
        uses: kubernetes-sigs/kubebuilder-release-tools@012269a88fa4c034a0acf1ba84c26b195c0dbab4 # tag=v0.4.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21

      - name: Checkout code
        uses: actions/checkout@v2    

      - name: Verify Go directive
        run: |
          make verify-go-directive
